# Generated by Django 4.2.1 on 2023-05-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto_aplicable', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lista_articulos', models.JSONField()),
                ('precio_total_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total_con_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
